function [labor,c,knext,labor_tauL,c_tauL,labor_tauK,c_tauK,labor_k,c_k,D] = getLaborCKnext(k,tauK,tauL,z,g,alpha,delta,gamma,eta,D)

labor=((g+tauK.*delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha))).^(1/(1-alpha));
c=(((1-tauL).*(1-alpha).*z.*k.^alpha)./(D.*labor.^(alpha+eta))).^(1/gamma);
knext=z.*k.^alpha.*labor.^(1-alpha)+(1-delta)*k-g-c;

%tauL derivatives
labor_tauL =(1/(1-alpha)).*((g+tauK.*delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha))).^(1/(1-alpha)-1).*...
                            (-(g+tauK.*delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha)).^2).*...
                            (1-alpha).*z.*k.^(alpha);
                        
c_tauL     =(1/gamma).*(((1-tauL).*(1-alpha).*z.*k.^alpha)./(D.*labor.^(alpha+eta))).^(1/gamma-1).*...
                        (((-1).*(1-alpha).*z.*k.^alpha)./(D.*labor.^(alpha+eta))+...
                         -((1-tauL).*(1-alpha).*z.*k.^alpha)./((D.*labor.^(alpha+eta)).^2).*(D.*(alpha+eta).*labor.^(alpha+eta-1)).*labor_tauL);
                     
%tauK derivatives
labor_tauK =(1/(1-alpha)).*((g+tauK.*delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha))).^(1/(1-alpha)-1).*...
                           ((-(g+tauK.*delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha)).^2).*alpha.*z.*k.^(alpha)+...
                            (delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha)));
                        
c_tauK     =(1/gamma).*(((1-tauL).*(1-alpha).*z.*k.^alpha)./(D.*labor.^(alpha+eta))).^(1/gamma-1).*...
                        (-((1-tauL).*(1-alpha).*z.*k.^alpha)./((D.*labor.^(alpha+eta)).^2).*(D.*(alpha+eta).*labor.^(alpha+eta-1)).*labor_tauK);
                    
%K derivatives
labor_k =(1/(1-alpha)).*((g+tauK.*delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha))).^(1/(1-alpha)-1).*...
                           ((-(g+tauK.*delta.*k)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha)).^2).*(alpha*tauK+(1-alpha)*tauL).*z.*alpha.*k.^(alpha-1)+...
                            (tauK.*delta)./((alpha*tauK+(1-alpha)*tauL).*z.*k.^(alpha)));
                        
c_k     =(1/gamma).*(((1-tauL).*(1-alpha).*z.*k.^alpha)./(D.*labor.^(alpha+eta))).^(1/gamma-1).*...
                        (((1-tauL).*(1-alpha).*z.*alpha.*k.^(alpha-1))./(D.*labor.^(alpha+eta))+...
                         -((1-tauL).*(1-alpha).*z.*k.^alpha)./((D.*labor.^(alpha+eta)).^2).*(D.*(alpha+eta).*labor.^(alpha+eta-1)).*labor_k);
                     
D = (c.^(-gamma)).*(c+knext)-D.*(labor.^eta).*labor;

end